// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TASK.DAL.Context;

namespace TASK.DAL.Migrations
{
    [DbContext(typeof(TaskDbContext))]
    [Migration("20210914103017_Add-Relations")]
    partial class AddRelations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TASK.DAL.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mobile")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Salary")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f138a31e-3c81-481e-92de-d873d020b4d4"),
                            Email = "ahmadsabry28@gmail.com",
                            Mobile = 1119790023,
                            Name = "Ahmed",
                            Salary = 6000f
                        },
                        new
                        {
                            Id = new Guid("80a83d08-b6fa-477a-801b-06ec518a12b9"),
                            Email = "ahmadsabry28@hotmail.com",
                            Mobile = 1119790023,
                            Name = "Sabry",
                            Salary = 7000f
                        },
                        new
                        {
                            Id = new Guid("cc24fc2d-9a8b-41f9-87ba-1b6c9112a7b8"),
                            Email = "ahmadsabry28@yahoo.com",
                            Mobile = 1119790023,
                            Name = "AhmedSabry",
                            Salary = 8000f
                        },
                        new
                        {
                            Id = new Guid("e8a5a26b-26ab-4a16-b280-60afcc5b56f9"),
                            Email = "ahmadsabry28@msn.com",
                            Mobile = 1119790023,
                            Name = "Ahmed",
                            Salary = 9000f
                        });
                });

            modelBuilder.Entity("TASK.DAL.Models.EmployeeTax", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmpId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("NetSalary")
                        .HasColumnType("real");

                    b.Property<float>("Tax")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("EmpId");

                    b.ToTable("EmployeeTaxs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55b29ec5-b130-4c96-acf0-e946a49b4a72"),
                            EmpId = new Guid("f138a31e-3c81-481e-92de-d873d020b4d4"),
                            NetSalary = 600f,
                            Tax = 50f
                        },
                        new
                        {
                            Id = new Guid("51feccbb-929e-4aa6-9e2d-dc9dfa0c0ed4"),
                            EmpId = new Guid("80a83d08-b6fa-477a-801b-06ec518a12b9"),
                            NetSalary = 700f,
                            Tax = 50f
                        });
                });

            modelBuilder.Entity("TASK.DAL.Models.EmployeeTax", b =>
                {
                    b.HasOne("TASK.DAL.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
